from PySide6.QtWidgets import QDialog, QVBoxLayout, QPushButton, QMessageBox
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWebEngineCore import QWebEngineProfile, QWebEngineCookieStore
from PySide6.QtCore import QUrl, Slot, QDateTime
import os

class LoginDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("YouTube 로그인 (YouTube Login)")
        self.resize(1024, 768)
        
        self.layout = QVBoxLayout(self)
        
        # Web Engine
        self.profile = QWebEngineProfile("youtube_login_profile", self)
        
        # Use LocalAppData to avoid permission/lock issues in project dir
        local_app_data = os.environ.get('LOCALAPPDATA', os.path.expanduser('~'))
        profile_path = os.path.join(local_app_data, 'LHCVideoDownloader', 'web_profile')
        if not os.path.exists(profile_path):
            os.makedirs(profile_path, exist_ok=True)
            
        self.profile.setPersistentStoragePath(profile_path)
        self.profile.setPersistentCookiesPolicy(QWebEngineProfile.PersistentCookiesPolicy.ForcePersistentCookies)
        
        self.webview = QWebEngineView()
        self.webview.setPage(QWebEngineView(parent=self).page()) # Hack to init page
        self.webview.setHtml("Loading...")
        
        # Use our isolated profile
        from PySide6.QtWebEngineCore import QWebEnginePage
        page = QWebEnginePage(self.profile, self.webview)
        self.webview.setPage(page)
        
        self.webview.setUrl(QUrl("https://accounts.google.com/ServiceLogin?service=youtube"))
        
        self.layout.addWidget(self.webview)
        
        # Save Button
        self.save_btn = QPushButton("로그인 완료 및 쿠키 저장 (Save Login)")
        self.save_btn.clicked.connect(self.save_cookies)
        self.save_btn.setStyleSheet("background-color: #d32f2f; color: white; padding: 10px; font-weight: bold;")
        self.layout.addWidget(self.save_btn)
        
    @Slot()
    def save_cookies(self):
        cookie_store = self.profile.cookieStore()
        self.cookie_store = cookie_store # Keep ref
        
        self.collected_cookies = []
        
        # Define callback
        def handle_cookie(cookie):
            self.collected_cookies.append(cookie)
            
        self.cookie_store.cookieAdded.connect(handle_cookie)
        self.cookie_store.loadAllCookies()
        
        self.save_btn.setText("저장 중... 잠시만 기다려주세요...")
        self.save_btn.setEnabled(False)
        
        from PySide6.QtCore import QTimer
        QTimer.singleShot(2000, self.finalize_save)

    def finalize_save(self):
        # Format to Netscape
        cookie_dir = os.path.abspath("libs/cookies")
        if not os.path.exists(cookie_dir):
            os.makedirs(cookie_dir)
            
        cookie_file_path = os.path.join(cookie_dir, "auth_cookies.txt")
        
        try:
            with open(cookie_file_path, "w", encoding="utf-8") as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file was generated by VideoDownloader\n\n")
                
                for cookie in self.collected_cookies:
                    domain = cookie.domain()
                    flag = "TRUE" if domain.startswith('.') else "FALSE"
                    path = cookie.path()
                    secure = "TRUE" if cookie.isSecure() else "FALSE"
                    expiry = str(int(cookie.expirationDate().toSecsSinceEpoch())) if not cookie.expirationDate().isNull() else "0"
                    name = cookie.name().data().decode('utf-8')
                    value = cookie.value().data().decode('utf-8')
                    
                    f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
            
            QMessageBox.information(self, "성공", f"쿠키가 성공적으로 저장되었습니다!\n앱 내 로그인 옵션을 사용하여 다운로드하세요.")
            self.accept()
            
        except Exception as e:
            QMessageBox.critical(self, "오류", f"쿠키 저장 실패: {str(e)}")
            self.save_btn.setText("다시 시도 (Retry)")
            self.save_btn.setEnabled(True)
